In [7]:
import torch
import tqdm
import os
import json
import numpy as np
from torch.utils.data import DataLoader, Dataset, TensorDataset

In [8]:

# class CNN_net(torch.nn.Module):
#     def __init__(self):
#         super(CNN_net,self).__init__()
#         self.conv1 = torch.nn.Sequential(
#             torch.nn.Conv2d(in_channels=2,
#                             out_channels=16,
#                             kernel_size=(3,3),
#                             stride=(1,1),
#                             padding=1),
#             torch.nn.BatchNorm2d(16),
#             torch.nn.ReLU(),
#             torch.nn.MaxPool2d(kernel_size=2)
#         )
#         self.conv2 = torch.nn.Sequential(
#             torch.nn.Conv2d(16,32,(3,3),(1,1),1),
#             torch.nn.BatchNorm2d(32),
#             torch.nn.ReLU(),
#             torch.nn.MaxPool2d(kernel_size=2)
#         )
#         self.conv3 = torch.nn.Sequential(
#             torch.nn.Conv2d(32,64,(3,3),(1,1),1),
#             torch.nn.BatchNorm2d(64),
#             torch.nn.ReLU(),
#             torch.nn.MaxPool2d(kernel_size=2)
#         )
#
#         self.conv4 = torch.nn.Sequential(
#             torch.nn.Conv2d(64,128,(3,3),(1,1),1),
#             torch.nn.BatchNorm2d(128),
#             torch.nn.ReLU(),
#             torch.nn.MaxPool2d(kernel_size=2)
#         )
#
#         self.mlp1 = torch.nn.Linear(3*3*128,4)
#
#     def forward(self, x):
#         x = self.conv1(x)
#         # print(x.shape)
#         x = self.conv2(x)
#         # print(x.shape)
#         x = self.conv3(x)
#         # print(x.shape)
#         x = self.conv4(x)
#         # print(x.shape)
#         x = x.view(x.size(0),-1)
#         # print(x.shape)
#         x = self.mlp1(x)
#         # print(x.shape)
#         # print(x)
#         return x


In [9]:

class CNN_net(torch.nn.Module):
    def __init__(self):
        super(CNN_net,self).__init__()
        self.conv1 = torch.nn.Sequential(
            torch.nn.Conv2d(in_channels=2,
                            out_channels=16,
                            kernel_size=(3,3),
                            stride=(1,1),
                            padding=1),
            torch.nn.BatchNorm2d(16),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2)
        )
        self.conv2 = torch.nn.Sequential(
            torch.nn.Conv2d(16,32,(3,3),(1,1),1),
            torch.nn.BatchNorm2d(32),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2)
        )
        self.conv3 = torch.nn.Sequential(
            torch.nn.Conv2d(32,64,(3,3),(1,1),1),
            torch.nn.BatchNorm2d(64),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2)
        )

        self.conv4 = torch.nn.Sequential(
            torch.nn.Conv2d(64,128,(3,3),(1,1),1),
            torch.nn.BatchNorm2d(128),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2)
        )

        self.mlp1 = torch.nn.Linear(3*3*128,12)
        self.mlp2=torch.nn.Linear(12, 4)

    def forward(self, x):
        x = self.conv1(x)
        # print(x.shape)
        x = self.conv2(x)
        # print(x.shape)
        x = self.conv3(x)
        # print(x.shape)
        x = self.conv4(x)
        # print(x.shape)
        x = x.view(x.size(0),-1)
        # print(x.shape)
        x = self.mlp1(x)
        # print(x.shape)
        x=self.mlp2(x)
        # print(x)
        return x


In [10]:
test_model_path='D:\\520_data\\model_for_project3\\new'
test_model_list=os.listdir(test_model_path)
test_model_list

['epoch_0_countOfFile0_Acc_0.27284392474572433_Loss_1.7036027831908984.pth',
 'epoch_0_countOfFile0_Acc_0.275334788433838_Loss_1.762751036729568.pth',
 'epoch_0_countOfFile200_Acc_0.6349163741092548_Loss_0.8292748133030162.pth',
 'epoch_10_countOfFile0_Acc_0.8956667777910567_Loss_0.26866016804407805.pth',
 'epoch_10_countOfFile200_Acc_0.8992189733165725_Loss_0.2567718841665181.pth',
 'epoch_11_countOfFile0_Acc_0.8960378913203465_Loss_0.26750586888729.pth',
 'epoch_11_countOfFile200_Acc_0.9008370178310889_Loss_0.25273884874030045.pth',
 'epoch_12_countOfFile0_Acc_0.89783055836861_Loss_0.26404917278350926.pth',
 'epoch_12_countOfFile200_Acc_0.9025910041894601_Loss_0.24878344655105272.pth',
 'epoch_13_countOfFile0_Acc_0.8989250287770236_Loss_0.2607274265625538.pth',
 'epoch_13_countOfFile200_Acc_0.9012568995917485_Loss_0.2525978943431228.pth',
 'epoch_14_countOfFile0_Acc_0.9002773916379945_Loss_0.2576088970288252.pth',
 'epoch_14_countOfFile200_Acc_0.9039630855253795_Loss_0.24568911285170

In [5]:
test_file_path='D:\\520_data\\data.tar\\data\\Data\\train_data\\1320.json'
with open(test_file_path, 'r') as data_reader:
    test_data=data_reader.read()
test_data=json.loads(test_data)

test_data_x=[]
test_data_y=[]

for i in test_data.keys():
    input_data_1 = [[0 for i1 in range(50)] for i2 in range(50)]
    one_train_data = test_data[i]
    agent_x, agent_y = one_train_data["agent_position"]
    input_data_1[agent_x][agent_y] = 1

    sub_test_data_x = [input_data_1, one_train_data["maze"]]
    test_data_x.append(sub_test_data_x)

    test_data_y.append(one_train_data["forward"])

test_data_x = torch.tensor(test_data_x, dtype=torch.float)
test_data_y = torch.tensor(test_data_y, dtype=torch.float)

data_set_train = TensorDataset(test_data_x, test_data_y)
test_data = DataLoader(dataset=data_set_train,
                       batch_size=1024,
                       shuffle=True)



KeyError: 'forward'

In [11]:
def get_forward(path, index):
    # 上下左右
    path_len = len(path)
    if index == path_len - 1:
        return [0, 0, 0, 0]
    else:
        x1, y1 = path[index]
        x2, y2 = path[index + 1]
        if x1 - 1 == x2:
            return [1, 0, 0, 0]
        elif x1 + 1 == x2:
            return [0, 1, 0, 0]
        elif y1 - 1 == y2:
            return [0, 0, 1, 0]
        elif y1 + 1 == y2:
            return [0, 0, 0, 1]
        else:
            return [1, 1, 1, 1]

In [12]:
test_file_path='D:\\520_data\\data.tar\\data\\Data\\train_data\\1320.json'
with open(test_file_path, 'r') as data_reader:
    test_data=data_reader.read()
test_data=json.loads(test_data)

test_data_x=[]
test_data_y=[]

for i in test_data.keys():
    one_train_data = test_data[i]
    path=one_train_data["path"]
    path_length=len(path)
    for index, (agent_x, agent_y) in enumerate(path):
        if index<path_length-1:
            input_data_1=[[0 for i1 in range(50)] for i2 in range(50)]
            target_x, target_y = one_train_data["target_position"]
            input_data_1[agent_x][agent_y] = 1
            input_data_1[target_x][target_y]=10
            sub_train_data_x = [input_data_1, one_train_data["maze"]]
            test_data_x.append(sub_train_data_x)
            test_data_y.append(get_forward(path, index))

test_data_x=test_data_x[:4056]
test_data_y=test_data_y[:4056]

test_data_x = torch.tensor(test_data_x, dtype=torch.float)
test_data_y = torch.tensor(test_data_y, dtype=torch.float)

data_set_train = TensorDataset(test_data_x, test_data_y)
test_data = DataLoader(dataset=data_set_train,
                       batch_size=1024,
                       shuffle=True)


In [13]:
loss_func = torch.nn.CrossEntropyLoss()

In [14]:
result={}

for index, test_model_file in enumerate(test_model_list):
    print(index)
    loss_list=[]
    acc_list=[]
    test_model=os.path.join(test_model_path, test_model_file)
    model=torch.load(test_model, map_location=torch.device('cpu'))
    model.eval()
    for test_data_x, test_data_y in test_data:
        predict=model(test_data_x)
        loss_list.append(loss_func(predict, test_data_y).item())
        acc_list.append(torch.eq(predict.argmax(1), test_data_y.argmax(1)).sum().float().item()/len(test_data_x))
    result[test_model_file]={}
    result[test_model_file]['acc']=np.mean(acc_list)
    result[test_model_file]['loss']=np.mean(loss_list)



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


In [15]:
result_copy=result.copy()
keys=list(result_copy.keys())
keys.sort(key=lambda t:result_copy[t]['acc'])
keys

['epoch_0_countOfFile0_Acc_0.27284392474572433_Loss_1.7036027831908984.pth',
 'epoch_0_countOfFile0_Acc_0.275334788433838_Loss_1.762751036729568.pth',
 'epoch_0_countOfFile200_Acc_0.6349163741092548_Loss_0.8292748133030162.pth',
 'epoch_1_countOfFile0_Acc_0.8458495040287833_Loss_0.3853090138007433.pth',
 'epoch_2_countOfFile200_Acc_0.8681968507260154_Loss_0.3289836595529006.pth',
 'epoch_1_countOfFile200_Acc_0.856097367536865_Loss_0.3594202863325807.pth',
 'epoch_3_countOfFile200_Acc_0.87792385728689_Loss_0.30614758407498377.pth',
 'epoch_4_countOfFile200_Acc_0.8818447180616994_Loss_0.297705175813991.pth',
 'epoch_5_countOfFile200_Acc_0.8884912305310954_Loss_0.28207100362658233.pth',
 'epoch_3_countOfFile0_Acc_0.8712550556355791_Loss_0.32421007332129353.pth',
 'epoch_2_countOfFile0_Acc_0.8634805416999516_Loss_0.34185700309582245.pth',
 'epoch_5_countOfFile0_Acc_0.8810549688327536_Loss_0.30013056118518877.pth',
 'epoch_4_countOfFile0_Acc_0.8782621822733534_Loss_0.30737176537513733.pth',

In [8]:
result_copy

{'epoch_0_Acc_0.771307986194638_Loss_0.41693937187145624.pth': {'acc': 0.7400390625000001,
  'loss': 0.4635235865910848},
 'epoch_10_Acc_0.7754555631403225_Loss_0.4074152831686711.pth': {'acc': 0.7531684027777779,
  'loss': 0.4540112018585205},
 'epoch_11_Acc_0.7755864118849352_Loss_0.40696871082982905.pth': {'acc': 0.7599247685185185,
  'loss': 0.4495169321695964},
 'epoch_12_Acc_0.7759231408211309_Loss_0.40672753454648153.pth': {'acc': 0.7596788194444445,
  'loss': 0.44435324271519977},
 'epoch_13_Acc_0.7761131672750494_Loss_0.40606264039462125.pth': {'acc': 0.7508391203703703,
  'loss': 0.449456254641215},
 'epoch_14_Acc_0.7761603379685011_Loss_0.40603726051975936.pth': {'acc': 0.7535300925925926,
  'loss': 0.44486716389656067},
 'epoch_15_Acc_0.7766100294512532_Loss_0.40549010344586817.pth': {'acc': 0.7496744791666666,
  'loss': 0.4443869690100352},
 'epoch_16_Acc_0.7765689643197495_Loss_0.4051238639068539.pth': {'acc': 0.7612774884259258,
  'loss': 0.44477038582166034},
 'epoch_17

In [9]:
test_data_x1=test_data_x[:10]
test_data_y1=test_data_y[:10]
predict=model(test_data_x1)
# print(test_data_x1.shape)
# print(predict.shape)
print(predict.argmax(1))
print(test_data_y1.argmax(1))


tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 1])
tensor([1, 1, 1, 1, 3, 3, 3, 3, 3, 1])


In [17]:
c=[]
c1=torch.tensor(c,dtype=torch.float)


a=torch.ones((2,50,50)).unsqueeze(0)

b=torch.ones((2,50,50)).unsqueeze(0)
c1=torch.concat((c1, a), dim=0)
c1=torch.concat((c1,b), dim=0)
c1.shape


torch.Size([2, 2, 50, 50])

In [21]:
a=[[1 for i in range(50)] for j in range(50)]
b=[[1 for i in range(50)] for j in range(50)]
c=[a,b]
c1=torch.tensor(c, dtype=float)
c1.shape

torch.Size([2, 50, 50])

In [96]:
a=torch.zeros((2,5,5))
b=[[1],(1,3),(1,2)]

c=[[0],[3],[0]]

a[b]=1
input_data=a
input_data[c]=1
input_data



tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [97]:
a=torch.tensor([1,2,3,4])
b=torch.tensor([2,2,4,4])
a/b

tensor([0.5000, 1.0000, 0.7500, 1.0000])

In [98]:
 a+1

tensor([2, 3, 4, 5])

In [103]:
a=0x61
ord('1')

49

In [1]:
a={"1":434, "2":123}
for i in a:
    print(i)

1
2
